#!/bin/bash
set -e

# LinkedIn Ads ML Pipeline - Master Deployment Script
# Orchestrates full deployment of the ML optimization pipeline

echo "=========================================="
echo "LinkedIn Ads ML Pipeline"
echo "Complete Deployment"
echo "=========================================="
echo ""
echo "This script will deploy the entire ML optimization pipeline:"
echo ""
echo "Phase 1: Infrastructure (IAM roles, S3 buckets, SNS)"
echo "Phase 2: Lambda Functions (Data Processor, Optimizer, Copy Generator)"
echo "Phase 3: EventBridge Schedules (Automated triggers)"
echo "Phase 4: SageMaker Setup (Code upload, ready for training)"
echo ""
echo "⚠️  NOTE: Model training and endpoint deployment are separate"
echo "   (requires sufficient data to be collected first)"
echo ""
read -p "Continue with deployment? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Deployment cancelled."
  exit 0
fi
echo ""

# Phase 1: Infrastructure
echo "=========================================="
echo "PHASE 1: Infrastructure"
echo "=========================================="
echo ""
./deploy-infrastructure.sh
echo ""

# Phase 2: Lambda Functions
echo "=========================================="
echo "PHASE 2: Lambda Functions"
echo "=========================================="
echo ""
./deploy-lambdas.sh
echo ""

# Phase 3: EventBridge Schedules
echo "=========================================="
echo "PHASE 3: EventBridge Schedules"
echo "=========================================="
echo ""
./deploy-schedules.sh
echo ""

# Phase 4: Athena Database Setup
echo "=========================================="
echo "PHASE 4: Athena Database Setup"
echo "=========================================="
echo ""
./setup-athena.sh
echo ""

echo "=========================================="
echo "🎉 DEPLOYMENT COMPLETE!"
echo "=========================================="
echo ""
echo "✅ Infrastructure deployed"
echo "✅ Lambda functions deployed"
echo "✅ EventBridge schedules created"
echo "✅ Athena database configured"
echo "✅ CloudWatch alarms created"
echo "✅ SageMaker code uploaded"
echo ""
echo "Pipeline Status: READY (collecting data)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "REQUIRED: Store Secrets in AWS Secrets Manager"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. LinkedIn Access Token:"
echo "   aws secretsmanager create-secret \\"
echo "     --name linkedin-access-token \\"
echo "     --secret-string '{\"access_token\":\"YOUR_LINKEDIN_TOKEN\"}'"
echo ""
echo "2. Anthropic API Key (for Claude):"
echo "   aws secretsmanager create-secret \\"
echo "     --name anthropic-api-key \\"
echo "     --secret-string '{\"api_key\":\"YOUR_ANTHROPIC_KEY\"}'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Active Automation Schedule"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Daily:"
echo "  • 6:00 AM UTC - Data processor prepares training data"
echo "  • 8:00 AM UTC - Optimizer analyzes and optimizes campaigns"
echo ""
echo "Weekly (Mondays):"
echo "  • 9:00 AM UTC - Copy generator creates new variations"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next Steps (After Data Collection)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once you have 30+ days of performance data:"
echo ""
echo "1. Train ML models:"
echo "   ./train-models.sh"
echo ""
echo "2. Deploy model endpoints (after training completes):"
echo "   ./deploy-endpoints.sh"
echo ""
echo "3. Update Lambda with endpoint names:"
echo "   ./update-lambda-endpoints.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Manual Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test individual components:"
echo ""
echo "  # Run data processor"
echo "  aws lambda invoke --function-name linkedin-ads-data-processor output.json"
echo ""
echo "  # Run optimizer"
echo "  aws lambda invoke --function-name linkedin-ads-optimizer output.json"
echo ""
echo "  # Generate ad copy"
echo "  aws lambda invoke --function-name linkedin-ads-copy-generator output.json"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Your LinkedIn Ads ML Pipeline is now live!"
echo ""
